"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import RoomContextProvider from "@/Contexts/RoomContext/RoomContextProvider";
import { CacheProvider } from "@chakra-ui/next-js";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen antialiased bg-[#1d1b1b] flex flex-col`}>
        <ChakraProvider>
          <RoomContextProvider>
            {children}
          </RoomContextProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
